### ISSUE TITLE
Several DKIM Selectors, SPF Status Reporting Issues

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/DomainSecurityScanner#17]
@wolveix First, thank you so much for improving DSS!

Following up as we are more closely working through a set of domains, I found the following three (3) additional DKIM selectors missing results from the latest DSS to consider for its catalog:  
    **s1
    s2
    qualtrics**
  
Here's a domain that DSS didn't report SPF or DKIM results, has DKIM selector of "qualtrics":  
**ugicorp.com**

EasyDMARC Domain Security Scanner site to compare with:
  https://easydmarc.com/tools/domain-scanner

**Comment by wolveix** [comment]
Hey @OrlandoMD! You're very welcome regarding the improvements to DSS, it's thanks to your feedback that we're able to improve it further :) 

Thanks for this information. While there may be value in including `s1` and `s2`, I'm not sure about `qualtrics` personally. I'll need to research it more. The only issue with expanding the list is that it requires an additional lookup for every domain. I'm working on parallelizing DNS requests (currently only bulk domains run concurrently, not each of their DNS lookups) which may trivialize this concern.

Regarding the missing SPF information for that domain, this is due to the issue addressed in #15. This domain seems to have an even larger SPF response than the other domain, requiring the buffer to be increased even further. Please see my example command below with the full response:

```
❯ ./bin/dss scan ugicorp.com --dnsBuffer 2048 --dkimSelector qualtrics
scanResult:
    domain: ugicorp.com
    dkim: v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCXf1qc5i1bhv5TLyEWR3uoqF2LKr/CGszInmpf/Gyi5VW5SfA4/rcv1mKs6kADC+L6jBfmtMiel0pFPtYzSThplfsKysc6t3/dQosxYSXxYXXmTdXQbGWKcJ9rTQSlXa9fHFdHOx/JaFGwyE3gvwAWF6IH6Q8jCm6ztZI/WfTCowIDAQAB
    dmarc: v=DMARC1; p=none; rua=mailto:dmarc_rua@emaildefense.proofpoint.com; ruf=mailto:dmarc_ruf@emaildefense.proofpoint.com; fo=1d1Mt/kWuxIrM4F1LIGZ01ZP4DNE1ZKsaKob2Sv022oZeKV+FR+W4zVqK2ailYQGOZL33Hwc2PvWVf4Rn58UL8Q==MS=ms787728055QWq6nc6VzT1iPf8JpQHQSq1ZTmCvIvk/kZz7BA3dhy19E2JH0OgWltUKo5ZNgYYJzQgcquIaLGYc8x077HJuw==MS=ms46967064ccc9p3j5230l5g0gtbasqv8jb6v=DMARC1; p=none; fo=1; rua=mailto:dmarc_rua@emaildefense.proofpoint.com; ruf=mailto:dmarc_ruf@emaildefense.proofpoint.comonetrust-domain-verification=46fcb9a7986d429da70a6d96595348c9docusign=233608f1-b0c9-40dd-ae4d-3c809bc50da4docusign=29ddd604-be23-4388-946a-b509f0763f45v=spf1 a:smtp.ugicorp.com ip4:64.95.144.196 ip4:162.247.216.0/22 ip4:192.30.205.55 ip4:192.30.204.55 ip4:216.162.32.70 ip4:216.162.32.71 include:spf-0024bf01.pphosted.com  include:_spf-dc8.sapsf.com include:_spf.salesforce.com include:spf.protection.outlook.com ~allpSTYt3mv1kYgY3kiXRWLW6YZz0pOD5c+AUHCnZHGi0wH508f4Ab+dgR0tXPzak1X2iLeDwbz75/raGq60chBng==
    mx:
        - mx0a-0024bf01.pphosted.com.
        - mx0b-0024bf01.pphosted.com.
    spf: v=spf1 a:smtp.ugicorp.com ip4:64.95.144.196 ip4:162.247.216.0/22 ip4:192.30.205.55 ip4:192.30.204.55 ip4:216.162.32.70 ip4:216.162.32.71 include:spf-0024bf01.pphosted.com  include:_spf-dc8.sapsf.com include:_spf.salesforce.com include:spf.protection.outlo
    duration: 79.589749ms
```
