### ISSUE TITLE
DKIM still not showing properly

### ISSUE THREAD

**Issue by hanzala123** [GlobalCyberAlliance/DomainSecurityScanner#9]
Hello again,

Thanks for making such a quick fix to the issue. Unfortunately, I am still facing the same issue. If i run `./dss-linux-amd64_1 scan reconfirm.nl -a --checkTls` using the latest binary. I don't get any dkim results. I have also tried compiling from source using the latest changes. Still not result.

**Comment by wolveix** [comment]
Hey! Sorry to hear that you're still experiencing this issue. Just to rule out using the wrong binary, could you report the output of `dss --version`?

Here's what I'm seeing with that same command:
```
❯ ./bin/dss scan reconfirm.nl -a --checkTls
scanResult:
    domain: reconfirm.nl
    dkim: v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkzHhI7060QXEzJRpmSJMCtAbbpOQr2Nw6EX+XS5NDk33cxoJcH5xm8ybMCujqZmUZWnrvqk+5VLnrdSnF9bLbj9Ta2z60QVRnJ571ICznHke4YhnuWL1re1bvLCSebLCsBpot4C82DAtwhRxm0mRdIO00R7Bcp04ngmzRhgK/VJ2rOxSZsEhkpjWxfg1LcaVG
    dmarc: v=DMARC1; p=reject; sp=reject; rua=mailto:f598f966@in.mailhardener.com; aspf=s; adkim=s; fo=1; ruf=mailto:dmarc@reconfirm.nl
    mx:
        - reconfirm-nl.mail.protection.outlook.com.
    spf: v=spf1 include:spf.protection.outlook.com ~all
    duration: 297.677667ms
advice:
    bimi:
        - We couldn't detect any active BIMI record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this.
    dkim:
        - DKIM is setup for this email server. However, if you have other 3rd party systems, please send a test email to confirm DKIM is setup properly.
    dmarc:
        - You are at the highest level! Please make sure to continue reviewing the reports and make the appropriate adjustments, if needed.
    domain:
        - Your domain is using TLS 1.3, no further action needed!
    mx:
        - You have a single mail server setup, but it's recommended that you have at least two setup in case the first one fails.
        - 'reconfirm-nl.mail.protection.outlook.com: Your domain is using TLS version 1.2, and should be upgraded to TLS 1.3.'
    spf:
        - SPF seems to be setup correctly! No further action needed.
```

**Comment by hanzala123** [comment]
The output of the version command is
```
dss version 2.2.2
```
I compiled it today after cloning the repository. The output I get is 

```
scanResult:
    domain: reconfirm.nl
    dmarc: v=DMARC1; p=reject; sp=reject; rua=mailto:f598f966@in.mailhardener.com; aspf=s; adkim=s; fo=1; ruf=mailto:dmarc@reconfirm.nl
    mx:
        - reconfirm-nl.mail.protection.outlook.com.
    spf: v=spf1 include:spf.protection.outlook.com ~all
    duration: 9.022472176s
advice:
    bimi:
        - We couldn't detect any active BIMI record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this.
    dkim:
        - We couldn't detect any active DKIM record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this.
    dmarc:
        - You are at the highest level! Please make sure to continue reviewing the reports and make the appropriate adjustments, if needed.
    domain:
        - Your domain is using TLS 1.3, no further action needed!
    mx:
        - You have a single mail server setup, but it's recommended that you have at least two setup in case the first one fails.
        - 'reconfirm-nl.mail.protection.outlook.com: Your domain is using TLS version 1.2, and should be upgraded to TLS 1.3.'
    spf:
        - SPF seems to be setup correctly! No further action needed.
```

BTW I am not using this tool anymore. I created my own module in python for my work. I just wanted to let you know of this issue.
